name: security-action
on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'veracode.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.png* *.pdf* *.md* *Dockerfile *.yml'
          path: .

      - name: Publicando Artefato
        uses: actions/upload-artifact@v2
        with:
          name: pacoteVeracode
          path: veracode.zip

  veracode-sast-pipeline_scan:
    needs: build
    runs-on: ubuntu-latest
    name: veracode pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.12
        with:
          vid: ${{ secrets.VEACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: "veracode.zip" 