name: security-action
on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Empacotamento dos arquivos
        uses: thedoctor0/zip-release@master
        with:
          filename: 'veracode.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.png* *.pdf* *.md* *Dockerfile *.yml'
          path: .

      - name: Publicando Artefato
        uses: actions/upload-artifact@v2
        with:
          name: pacoteVeracode
          path: veracode.zip

  veracode-sast-pipeline_scan:
    needs: package
    runs-on: ubuntu-latest
    name: veracode pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: pacoteVeracode

      - name: veracode pipeline-scan
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.15
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: "veracode.zip"

  veracode-sca:
    needs: package
    runs-on: ubuntu-latest
    name: veracode sca

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: run veracode sca
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.10
        with:
          github_token: ${{ secrets.GB_TOKEN }}

  veracode-iac-scan:
    needs: package
    runs-on: ubuntu-latest
    name: veracode container iac secrets scanning
      
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Veracode Container/IaC/Secrets Scanning
        uses: veracode/container_iac_secrets_scanning@v1.0.2
        with: 
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          command: "scan" 
          type: "directory"
          format: "table"
          debug: false
          fail_build: false